# Supabase Configuration File

[functions.delete-user]
verify_jwt = true

[functions.generate-notifications]
verify_jwt = false  # Cron jobs don't need authentication

[functions.generate-notifications.cron]
schedule = "30 3 * * *"  # Daily at 3:30 AM UTC (9:00 AM IST)

